### ISSUE TITLE
Define a multi-DCC use case

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/usecases#1]
Start: 1/1/20
End: 7/1/20

**Comment by RLC-DCPPC** [comment]
If one of the existing UCs suffices, by all means let's use that. But this might be an opportunity for something (or more than one something) to be developed. Perhaps even for the rumored December demo.

**Comment by ACharbonneau** [comment]
post june multi-dcc use case related: https://github.com/nih-cfde/usecases/pull/3
