### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/usecases#14]
We need a style guide for this repo. It should include #13 as well as some other points i have from Lee asking me questions. I'll add them to this thread.

**Comment by ACharbonneau** [comment]
> Question for you: Would you prefer a single pull request that includes both the new files for this use case AND the changes to the existing pages that link to them, or two separate pull requests: one with the new files without the index pages updated, and a separate one for the changes to the existing files? 

One biggish PR is better, that lets me get the branch and render the changes locally to make sure it all looks right before I push it out. 

For the index, it is automatically created by the yaml headers. As long as you specify the correct parent in any of your new files,  it will be automagically added to the right index page.

**Comment by marisalim** [comment]
@ACharbonneau anything i can do here to help?

**Comment by ACharbonneau** [comment]
AFAIK no one has started this :)

**Comment by marisalim** [comment]
Ok, I can get started - pointers on how it should look and where it should go? is it just for the repo (part of a README), or part of the website?

**Comment by ACharbonneau** [comment]
it can be the readme

**Comment by marisalim** [comment]
#30 in progress

**Comment by marisalim** [comment]
(update: the style guide exists [here](https://cfde-usecases.readthedocs-hosted.com/en/latest/about/contributing/), but awaiting website automation features to edit the PR instruction steps)

**Comment by marisalim** [comment]
this doc has been revamped for the new UCL repo. now lives here https://github.com/nih-cfde/use-case-library-build/blob/latest/templates/CONTRIBUTING.md
