### ISSUE TITLE
fix broken persona and obj links

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/usecases#24]
On Use Cases pages, some persona and objective links are broken. E.g., 
https://cfde-usecases.readthedocs-hosted.com/en/latest/use-cases/uc0001-researcher-browse-and-filter/

[persona](https://cfde-usecases.readthedocs-hosted.com/en/latest/use-cases/personas/clinical-researcher)
[objective](https://cfde-usecases.readthedocs-hosted.com/en/latest/use-cases/objectives/multi-dcc-comparison)

**Comment by ACharbonneau** [comment]
:( oops. Not sure if the links are just bad or if the content is missing...if the content is broken assign me and I'll write some :)

**Comment by marisalim** [comment]
looks like the content is there but they're missing the `.md` extension.

**Comment by marisalim** [comment]
in PR now https://github.com/nih-cfde/usecases/pull/26
