### ISSUE TITLE
Use case for UI landing page

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/usecases#4]
subtask of https://github.com/nih-cfde/cfde-deriva/issues/45

- What personas are we trying to target?
- What information should the landing page have?

**Comment by ACharbonneau** [comment]
ideas from owens collection of other portal examples: 

https://drive.google.com/drive/u/1/folders/1lyHkq-YKe7b3_tyMHweMDlE4XEkfr2ON

**Comment by RLC-DCPPC** [comment]
The landing page should be linked to from the public site (nih-cfde.org) as described in the [Site Design Plan](https://docs.google.com/document/d/1WGQq0b66cWSqSPMLneeixc5EiAe4vkc2t_OyKB4tPeo/edit)

**Comment by ACharbonneau** [comment]
First draft of UI landing page: https://drive.google.com/a/ucdavis.edu/file/d/1vY_hBCtwNEtCWBK1dkkKttN5o14QkX4c/view?usp=sharing

**Comment by RLC-DCPPC** [comment]
> First draft of UI landing page: 

This is quite nice!

https://drive.google.com/a/ucdavis.edu/file/d/1vY_hBCtwNEtCWBK1dkkKttN5o14QkX4c/view?usp=sharing

Are you working on similar views for the portal and dashboard functionality?

**Comment by jrchudy** [comment]
Recent screens shown this morning (4/28), also added to the drive:
https://drive.google.com/a/isi.edu/file/d/1aUb4TpX7QG3VX3qJtDP8tMPDQUDNPvAf/view?usp=sharing

**Comment by ACharbonneau** [comment]
The idea here is that use cases help us define what a user should be able to do, and so we should probably try to write all aspects of the user experience as use cases. What we'd like here, is to write up a use case about a users actual experience getting from the landing page to using data. Ideally, I would have had time to do this months ago when I made the issue, before all the drafts were made and before the portal was mostly written...but...time. Still, it would be good to write it anyway, even if it's a bit retrospective now. In particular, because writing out how a thing should work can help us find ways in which we can improve what we have so far.
