### ISSUE TITLE
Epic 1 Use case

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/usecases#54]
Need to create a new use case to reflect Epic 1. 

use https://docs.google.com/document/d/1WV9Y2KR-tTXQlHxq7fDQztHvuK3DuLwh89-zVLi3JmY/edit as basis

**Comment by ACharbonneau** [comment]
Use case in progress https://github.com/nih-cfde/usecases/blob/epic1/docs/use-cases/uc0006-dcc-validates-data.md

Still needs most tasks and pretty much all requirements

Also need to find out for sure whether we're including a 'approve button' or if that is 100% out of band

**Comment by marisalim** [comment]
what is the 'approve button'?
