### ISSUE TITLE
Add icons for tracking

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/usecases#6]
"Lora approved"
"For June Demo"

**Comment by ACharbonneau** [comment]
The two that need these tags are UC0001 and UC0002

**Comment by ACharbonneau** [comment]
see: https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#icons

**Comment by jeremywalter** [comment]
What icons do we want to use for this purpose?  Or are we looking for more of a GitHub style tag that renders in the website? Or a random icon that has a legend somewhere to identify what it represents?

**Comment by ACharbonneau** [comment]
I was thinking like a github tag? But I'm good with a picture that has a word mouseover. Honestly, if it's what can happen by the demo, a reasonably straightforward icon that you need to go reference is fine. 
More user friendly is better, but at this point I just need *something*. I promised to do this months ago and just haven't had time :(

**Comment by ACharbonneau** [comment]
well that took forever, but I figured out a way to do it.

**Comment by ACharbonneau** [comment]
https://github.com/nih-cfde/usecases/pull/19
